# Generated by Django 4.1.2 on 2022-10-17 12:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('study', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studylog',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='outstudy',
            name='log',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='study.studylog'),
        ),
        migrations.AddField(
            model_name='instudy',
            name='log',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='study.studylog'),
        ),
    ]
