# Generated by Django 4.1.2 on 2022-10-19 02:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_follow'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='follow',
            table='follow',
        ),
    ]
